import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Image from "next/image";
import About from "../components/About";
import { Link } from "@mui/material";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Priceless</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1> :בחר רשת</h1>
      <div className={styles.supers}>
        <div>
          <label htmlFor="victory">
            <h4>ויקטורי</h4>
            <Image src="/victory.jpg" width={200} height={200} alt="victory" />
            <input type="checkbox" id="victory" />
          </label>
        </div>
        <div>
          <label htmlFor="shufersal">
            <h4>שופרסל</h4>
            <Image
              src="/shufersal.png"
              width={200}
              height={200}
              alt="sufersal"
            />
            <input type="checkbox" id="shufersal" />
          </label>
        </div>
        <div>
          <label htmlFor="rami-levi">
            <h4>רמי לוי</h4>
            <Image
              src="/rami-levi.png"
              width={200}
              height={200}
              alt="rami-levi"
            />
            <input type="checkbox" id="rami-levi" />
          </label>
        </div>
      </div>
      <Link href="/Cart">
        <button>Lets find the priceless</button>
      </Link>
      <Slider />
      <About />
    </div>
  );
}
